### PR TITLE
optional get/set syntax; operator<(); acces to reference vector

### PR DESCRIPTION
**Pull request by gaede**
- add option -g [--getSyntax] for createing getters and setters
   as getMember()/setMember()

 - add operator<() for Objects and ConstObjects so that they can be stored in maps

 - add getter for reference vector (additional to begin/end iterators)

 - updated (re-generated) example data model accordingly
   ( no change in any other code)

### CODE REVIEW

**Comment by hegner** [comment]
The getter for the reference vector will not work as you made it now. If you look at the iterators you will see why.

**Comment by gaede** [comment]
yep - that was a bit quick on my side (at least it compiled and ran ;-) ) 
it is removed again, which is a petty as in LCIO we use references to vectors rather than iterators ...

**Comment by hegner** [comment]
For storing things in a set a little test would be nice. So that we don't spoil that usage accidentally on refactoring. 

What concerns getting a vector of the references - let's discuss use cases via email. Unfortunately std::array_view didn't find its way into the C++14 standard. Otherwise that would have been the solution to it.

**Comment by gaede** [comment]
Test case added.
I have written a simple vector_view<T> 
 https://stash.desy.de/projects/IL/repos/plcio/browse/source/include/vector_view.h
which could be beautified and added to podio if need.
Currently used as extra code in plcio, eg:
` vector_view<ConstMCParticle> getParents() const { return vector_view<ConstMCParticle>( parents_begin(), parents_end() , parents_size() ) ; }`

We could think about adding an easy way of configuring which methods beyond the standard ones are created in podio, e.g. by including user_template.py.
This way one could choose whether to create an access to the reference vector.

**Comment by hegner** [comment]
Thanks. 

You could have a look at https://github.com/rhysd/array_view . For user templates we have to see where this would lead us to... feature creep and such ;-)

**Pull request merged**
